"""empty message

Revision ID: 21891fc4fd9a
Revises: 69487029c3bc
Create Date: 2020-05-25 18:06:50.713981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21891fc4fd9a'
down_revision = '69487029c3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed', 'email')
    # ### end Alembic commands ###
