"""empty message

Revision ID: 288459413bc4
Revises: 
Create Date: 2020-06-05 13:28:09.598545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288459413bc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('books',
    sa.Column('serialno', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('datein', sa.DateTime(), nullable=True),
    sa.Column('addedby', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('serialno'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fixed',
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('oname', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('reg_date', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('hostel',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('booked_hostel',
    sa.Column('bookeddate', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hostel', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['fixed.name'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('borrowed_books',
    sa.Column('serialno', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('borrowed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['fixed.name'], ),
    sa.ForeignKeyConstraint(['serialno'], ['books.serialno'], ),
    sa.PrimaryKeyConstraint('serialno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrowed_books')
    op.drop_table('booked_hostel')
    op.drop_table('hostel')
    op.drop_table('fixed')
    op.drop_table('books')
    op.drop_table('admins')
    # ### end Alembic commands ###
