"""empty message

Revision ID: 4ab6b99ddf9f
Revises: 8c584beee870
Create Date: 2020-06-11 16:58:50.545108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab6b99ddf9f'
down_revision = '8c584beee870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['fixed.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('number')
    # ### end Alembic commands ###
