"""empty message

Revision ID: d311eb4f8f18
Revises: 4ab6b99ddf9f
Create Date: 2020-07-31 14:25:10.149684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd311eb4f8f18'
down_revision = '4ab6b99ddf9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('return_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowed_books', 'return_date')
    # ### end Alembic commands ###
